services:
  mkdocs:
    build:
      context: .
      dockerfile: ./.local/docs/Dockerfile
    ports:
      - "9898:8000"
    volumes:
      - .:/docs

  trivy:
    profiles:
    - manual
    image: aquasec/trivy:0.69.3
    working_dir: /srv
    volumes:
      - .:/srv