// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orca/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagType int32

const (
	FlagType_FLAG_TYPE_STRING FlagType = 0
	FlagType_FLAG_TYPE_BOOL   FlagType = 1
)

// Enum value maps for FlagType.
var (
	FlagType_name = map[int32]string{
		0: "FLAG_TYPE_STRING",
		1: "FLAG_TYPE_BOOL",
	}
	FlagType_value = map[string]int32{
		"FLAG_TYPE_STRING": 0,
		"FLAG_TYPE_BOOL":   1,
	}
)

func (x FlagType) Enum() *FlagType {
	p := new(FlagType)
	*p = x
	return p
}

func (x FlagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagType) Descriptor() protoreflect.EnumDescriptor {
	return file_orca_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (FlagType) Type() protoreflect.EnumType {
	return &file_orca_plugin_v1_plugin_proto_enumTypes[0]
}

func (x FlagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagType.Descriptor instead.
func (FlagType) EnumDescriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type FlagSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Usage     string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Type      FlagType               `protobuf:"varint,4,opt,name=type,proto3,enum=orca.plugin.v1.FlagType" json:"type,omitempty"`
	// Default value, encoded as a string regardless of type.
	Default       string `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagSpec) Reset() {
	*x = FlagSpec{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagSpec) ProtoMessage() {}

func (x *FlagSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagSpec.ProtoReflect.Descriptor instead.
func (*FlagSpec) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *FlagSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagSpec) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagSpec) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *FlagSpec) GetType() FlagType {
	if x != nil {
		return x.Type
	}
	return FlagType_FLAG_TYPE_STRING
}

func (x *FlagSpec) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Use           string                 `protobuf:"bytes,1,opt,name=use,proto3" json:"use,omitempty"`
	Short         string                 `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"`
	Long          string                 `protobuf:"bytes,3,opt,name=long,proto3" json:"long,omitempty"`
	Flags         []*FlagSpec            `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Subcommands   []*CommandSpec         `protobuf:"bytes,5,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CommandSpec) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *CommandSpec) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CommandSpec) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *CommandSpec) GetFlags() []*FlagSpec {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CommandSpec) GetSubcommands() []*CommandSpec {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

type GetCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandsRequest) Reset() {
	*x = GetCommandsRequest{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsRequest) ProtoMessage() {}

func (x *GetCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetCommandsRequest) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type GetCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandSpec         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandsResponse) Reset() {
	*x = GetCommandsResponse{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandsResponse) ProtoMessage() {}

func (x *GetCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetCommandsResponse) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommandsResponse) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of the commands from the plugin's top-level command down to the leaf
	// being executed, e.g. ["k8s", "ctx"].
	CommandPath []string `protobuf:"bytes,1,rep,name=command_path,json=commandPath,proto3" json:"command_path,omitempty"`
	Args        []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Flag values keyed by flag name, encoded as strings.
	Flags         map[string]string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetCommandPath() []string {
	if x != nil {
		return x.CommandPath
	}
	return nil
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orca_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_orca_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_orca_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_orca_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1borca/plugin/v1/plugin.proto\x12\x0eorca.plugin.v1\"\x9a\x01\n" +
	"\bFlagSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.orca.plugin.v1.FlagTypeR\x04type\x12\x18\n" +
	"\adefault\x18\x05 \x01(\tR\adefault\"\xb8\x01\n" +
	"\vCommandSpec\x12\x10\n" +
	"\x03use\x18\x01 \x01(\tR\x03use\x12\x14\n" +
	"\x05short\x18\x02 \x01(\tR\x05short\x12\x12\n" +
	"\x04long\x18\x03 \x01(\tR\x04long\x12.\n" +
	"\x05flags\x18\x04 \x03(\v2\x18.orca.plugin.v1.FlagSpecR\x05flags\x12=\n" +
	"\vsubcommands\x18\x05 \x03(\v2\x1b.orca.plugin.v1.CommandSpecR\vsubcommands\"\x14\n" +
	"\x12GetCommandsRequest\"N\n" +
	"\x13GetCommandsResponse\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.orca.plugin.v1.CommandSpecR\bcommands\"\xc2\x01\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\fcommand_path\x18\x01 \x03(\tR\vcommandPath\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12?\n" +
	"\x05flags\x18\x03 \x03(\v2).orca.plugin.v1.ExecuteRequest.FlagsEntryR\x05flags\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*4\n" +
	"\bFlagType\x12\x14\n" +
	"\x10FLAG_TYPE_STRING\x10\x00\x12\x12\n" +
	"\x0eFLAG_TYPE_BOOL\x10\x012\xb5\x01\n" +
	"\x0fCommandProvider\x12V\n" +
	"\vGetCommands\x12\".orca.plugin.v1.GetCommandsRequest\x1a#.orca.plugin.v1.GetCommandsResponse\x12J\n" +
	"\aExecute\x12\x1e.orca.plugin.v1.ExecuteRequest\x1a\x1f.orca.plugin.v1.ExecuteResponseB7Z5github.com/adamkirk/orca/pkg/plugin/proto/v1;pluginv1b\x06proto3"

var (
	file_orca_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_orca_plugin_v1_plugin_proto_rawDescData []byte
)

func file_orca_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_orca_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_orca_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orca_plugin_v1_plugin_proto_rawDesc), len(file_orca_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_orca_plugin_v1_plugin_proto_rawDescData
}

var file_orca_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orca_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orca_plugin_v1_plugin_proto_goTypes = []any{
	(FlagType)(0),               // 0: orca.plugin.v1.FlagType
	(*FlagSpec)(nil),            // 1: orca.plugin.v1.FlagSpec
	(*CommandSpec)(nil),         // 2: orca.plugin.v1.CommandSpec
	(*GetCommandsRequest)(nil),  // 3: orca.plugin.v1.GetCommandsRequest
	(*GetCommandsResponse)(nil), // 4: orca.plugin.v1.GetCommandsResponse
	(*ExecuteRequest)(nil),      // 5: orca.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),     // 6: orca.plugin.v1.ExecuteResponse
	nil,                         // 7: orca.plugin.v1.ExecuteRequest.FlagsEntry
}
var file_orca_plugin_v1_plugin_proto_depIdxs = []int32{
	0, // 0: orca.plugin.v1.FlagSpec.type:type_name -> orca.plugin.v1.FlagType
	1, // 1: orca.plugin.v1.CommandSpec.flags:type_name -> orca.plugin.v1.FlagSpec
	2, // 2: orca.plugin.v1.CommandSpec.subcommands:type_name -> orca.plugin.v1.CommandSpec
	2, // 3: orca.plugin.v1.GetCommandsResponse.commands:type_name -> orca.plugin.v1.CommandSpec
	7, // 4: orca.plugin.v1.ExecuteRequest.flags:type_name -> orca.plugin.v1.ExecuteRequest.FlagsEntry
	3, // 5: orca.plugin.v1.CommandProvider.GetCommands:input_type -> orca.plugin.v1.GetCommandsRequest
	5, // 6: orca.plugin.v1.CommandProvider.Execute:input_type -> orca.plugin.v1.ExecuteRequest
	4, // 7: orca.plugin.v1.CommandProvider.GetCommands:output_type -> orca.plugin.v1.GetCommandsResponse
	6, // 8: orca.plugin.v1.CommandProvider.Execute:output_type -> orca.plugin.v1.ExecuteResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_orca_plugin_v1_plugin_proto_init() }
func file_orca_plugin_v1_plugin_proto_init() {
	if File_orca_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orca_plugin_v1_plugin_proto_rawDesc), len(file_orca_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orca_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_orca_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_orca_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_orca_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_orca_plugin_v1_plugin_proto = out.File
	file_orca_plugin_v1_plugin_proto_goTypes = nil
	file_orca_plugin_v1_plugin_proto_depIdxs = nil
}
