# See: https://goreleaser.com/ci/actions/#workflow
name: "_INC: Trivy Scan"

on:
  workflow_call:

jobs:
  trivy_scan:
    name: Trivy Scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        version: v0.75.0
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
        # Make trivy fail when it finds a vulnerability
        exit-code: 1
