name: "CI: Scan"
run-name: "CI: Scan #${{ github.event.pull_request.number }}"

on:
  pull_request:

jobs:
  trivy_scan:
    name: Trivy Scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
        # Make trivy fail when it finds a vulnerability
        exit-code: 1
