name: "RELEASE: Create"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_next_tag:
    name: Generate next Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    outputs:
      next_version: ${{ steps.expose_next_version.outputs.next_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Create empty file
        run: echo "" > nextversion
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Expose next version output
        id: expose_next_version
        run: echo "next_version=$(cat nextversion)" >> "$GITHUB_OUTPUT"

  publish_release:
    # If it's empty, we don't need to create a new release
    if: needs.generate_next_tag.outputs.next_version != ""
    name: "Publish release"
    needs:
      - generate_next_tag
    uses: ./.github/workflows/_publish_release_for_tag.yaml
    secrets: inherit
    with:
      tag: ${{ needs.generate_next_tag.outputs.next_version }}