name: "DOCS: Generate Badges"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install reporter
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report@latest
      - name: Run tests
        run: go test ./... -coverprofile=./cover.out -covermode=set -coverpkg=./...
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        if: always()
        with:
          config: ./.testcoverage.yml
          git-token: ${{ secrets.GITHUB_TOKEN }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges